// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          margin: "0",
          padding: "0",
          width: "100%",
          overflowX: "hidden",
          backgroundColor: "#EDEFF0"
        }}
      >
          <Head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
        <main
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
